Authorization branch PR
mertkantaroglu/Blog-App pull request #11
Opened 2023-06-01 18:13 UTC by mertkantaroglu

Hello,

In this branch me and @rica213;

- Installed CanCanCan in the project.
- Added a `role` column to the users table by using a migration.
- Added functionality where the user can delete a post if it is theirs or if they have an admin role. Used CanCanCan for this authorization.
    - Implemented the post deleting functionality. Added the "Delete" button to the view and made sure that only authorized users can see it.
- Added functionality where the user can delete a comment if it is theirs or if they have an admin role. Used CanCanCan for this authorization.
    - Implemented the comment deleting functionality. Added the "Delete" button to the view and made sure that only authorized users can see it.
- Fixed linter errors

Looking forward to hearing from you.

Thanks.

2023-06-01 18:43 UTC, CollinsTatang requested changes
Hi @mertkantaroglu , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

## Required changes 
It's ok to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality and help you get a better job.
_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 18:43 UTC, CollinsTatang commented on app/models/user.rb
> +  end
Great job

- Creating your admin role method in the User model :+1:

2023-06-01 18:43 UTC, CollinsTatang commented on app/controllers/posts_controller.rb
> +    redirect_to user_posts_path(@user)
- [ ] Kindly make use of **CanCanCan** for Post authorization in the Post Controller before any action.
```ruby
class PostsController < ApplicationController
    load_and_authorize_resource

    ...
  end
```

2023-06-01 19:06 UTC, mertkantaroglu commented on app/models/user.rb
> +  end
Thank you @CollinsTatang

2023-06-02 11:14 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project meets all changes requested by the previous reviewer ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 11:20 UTC, merged